import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.environ.get('BINANCE_API_KEY_TEST')
API_SECRET = os.environ.get('BINANCE_API_SECRET_TEST')
DB_PATH  = "trading_info.db"

INTERVAL_IN_MINUTES = [5, 10, 15, 30, 60]
EXECUTION_FREQUENCY_MINUTES = 2

PERCENTAGE_THRESHOLD = 9
UNDER_PURCHASE_PERCENTAGE = 5
UNDER_HIGHEST_PERCENTAGE = 2
ABOVE_PURCHASE_PERCENTAGE = 5000

TESTING_INITIAL_BALANCE = 30
OPERATION_VALUE_PERCENTAGE = 5
