import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.environ.get('BINANCE_API_KEY_TEST')
API_SECRET = os.environ.get('BINANCE_API_SECRET_TEST')
DB_PATH  = "trading_info.db"

INTERVAL_IN_MINUTES = [5, 10, 15, 30, 60]
EXECUTION_FREQUENCY_MINUTES = 5

PERCENTAGE_THRESHOLD = 10
UNDER_PURCHASE_PERCENTAGE = 3
UNDER_HIGHEST_PERCENTAGE = 3
ABOVE_PURCHASE_PERCENTAGE = 200

TESTING_INITIAL_BALANCE = 100
OPERATION_VALUE_PERCENTAGE = 5
