name: Automatic Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
          docker build -t altacrypto:latest .

    - name: Save Docker image to a tar file
      run: |
          docker save altacrypto:latest -o altacrypto.tar

    - name: Create SSH Key
      run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ./alta_aws_keypair.pem
          chmod 0400 ./alta_aws_keypair.pem

    - name: Create .ssh directory
      run: |
          mkdir -p ~/.ssh

    - name: Add EC2 Host to Known Hosts
      run: |
          ssh-keyscan -H -v "18.230.59.126" >> ~/.ssh/known_hosts

    - name: Copy Docker image to EC2
      run: |
          scp -i ./alta_aws_keypair.pem ./altacrypto.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

    - name: SSH and load Docker image on EC2
      run: |
          ssh -t -i ./alta_aws_keypair.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          docker load -i /home/${{ secrets.EC2_USER }}/altacrypto.tar
          docker stop altacrypto || true
          docker rm altacrypto || true
          docker run -d -e MONGO_USER=${{ secrets.MONGO_USER }} -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} --name altacrypto -p 5000:5000 altacrypto:latest

