name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    #
    # - name: Build Docker image
    #   run: |
    #     docker build -t altacrypto:latest .
    #
    # - name: Save Docker image to a tar file
    #   run: |
    #     docker save altacrypto:latest -o altacrypto.tar
    #
    - name: Create SSH Key
      run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ./alta_aws_pair_key.pem
          chmod 0400 ./alta_aws_pair_key.pem
    #
    # - name: Copy Docker image to EC2
    #   run: |
    #       scp -i .alta_aws_pair_key.pem ./altacrypto.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/altacrypto
    #
    # - name: SSH and load Docker image on EC2
    #   run: |
    #       ssh -i .alta_aws_pair_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}
    #       docker load -i /home/${{ secrets.EC2_USER }}/altacrypto.tar
    #       docker stop altacrypto || true
    #       docker rm altacrypto || true
    #       docker run -d -e MONGO_USER=${{ secrets.MONGO_USER }} -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} --name altacrypto -p 5000:5000 altacrypto:latest

    - name: Clean SSH Key
      run: |
          rm ./alta_aws_pair_key.pem
