name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t altacrypto:latest .

    - name: Save Docker image to a tar file
      run: |
        docker save altacrypto:latest -o altacrypto.tar

    - name: Copy Docker image to EC2
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "altacrypto.tar"
        target: "${{ secrets.EC2_TARGET }}/altacrypto.tar"

    - name: SSH and load Docker image on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load -i /home/${{ secrets.EC2_USER }}/altacrypto.tar
          docker stop altacrypto || true
          docker rm altacrypto || true
          docker run -d --name altacrypto -p 80:80 altacrypto:latest
